### ISSUE TITLE
AutoType password character limitations?

### ISSUE THREAD

**Issue by zetheroo** [Jonny007-MKD/password-dialog-title#2]
One thing I experienced is that passwords with asterisks or the letter 'z' don't seem to work.
What I mean by this is that even though the passwords get filled in, they don't authenticate. If I manually copy/paste the password from Keepassxc it authenticates.

After trying all kinds of passwords on a number of entries I was experiencing this issue with I narrowed it down to removing the asterisks in two of my passwords, and then the letter 'z' in several other passwords.

**Comment by Jonny007-MKD** [comment]
Hi,
sorry, but this definitely is not an issue of my addon :) I do have asterisks and zs in my passwords and AutoType works fine.

Still I want to help you with this issue.

1. As a first step you could try to AutoType into a text editor and see if the password is typed exactly as you copy it into the line below. If not, this is a KeePassXC issue.

2. As a second step you could start Thunderbird debugging (Tools > Developer Tools > Developer Toolbox). Then you make Thunderbird open a password dialog (e.g. by skipping it after startup and then switching to the inbox) and switch the context in the debugger to the chrome://global/content/commonDialog.xul (some dropdown icon in the upper right corner of the debugger). Now you can run AutoType (without {ENTER} so that the dialog stays open) and have a look at the filled in password with `document.getElementById('#password1Textbox').value`.

**Comment by zetheroo** [comment]
Ah, ok. I'll do some more troubleshooting then. Are you not using Keepassxc with your TB plugin?

**Comment by Jonny007-MKD** [comment]
Yes, I do, and everything works

**Comment by zetheroo** [comment]
I tried it now on my home laptop and it works with asterisks and 'z' in the password. Really weird. I will try again on my work laptop tomorrow.

**Comment by zetheroo** [comment]
I tested with the text file like you suggested and the issue seems to have been caused by me having two keyboard languages installed. It's working now. :)
